### ISSUE TITLE
rvierdiiev - MultiInvoker will not be able to commit sevral prices to the oracle

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-perennial-judging#23]
rvierdiiev

medium

# MultiInvoker will not be able to commit sevral prices to the oracle
## Summary
MultiInvoker will not be able to commit sevral prices to the oracle.
## Vulnerability Detail
MultiInvoker can be used to execute several actions in same tx.
It's possible that keeper would like to execute [commit price](https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-extensions/contracts/MultiInvoker.sol#L300-L307) several times. This action [sends all `msg.value`](https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-extensions/contracts/MultiInvoker.sol#L303) with the call to the oracle.
Because of that all amount is sent along with the first call and another one will revert as there will be no payment for the oracle data check.
## Impact
Several commit prices will not work.
## Code Snippet
Provided above
## Tool used
VsCode
Manual Review

## Recommendation
Allow caller to provide amount for each commit call.

**Comment by rvierdiyev** [comment]
Escalate
I believe that it was wrongly excluded. This was confirmed by sponsor, so i would like him to see this report.

**Comment by sherlock-admin2** [comment]
> Escalate
> I believe that it was wrongly excluded. This was confirmed by sponsor, so i would like him to see this report.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@arjun-io

**Comment by arjun-io** [comment]
This is valid.

Fix: https://github.com/equilibria-xyz/perennial-v2/pull/61

**Comment by 141345** [comment]
seems low severity.

Because users can do it in different tx, no big loss without multiple commit at once.

**Comment by hrishibhat** [comment]
@rvierdiyev  
This seems to be low impact. There is no loss. Seems like a missing feature.

**Comment by rvierdiiev** [comment]
There is loss. Keeper's funds, that were spent on gas. Contract was designed to allow that, in order to make it more profitable for keepers to execute txs. Because of this, they will spend more funds. Am i correct with this assumption, @arjun-io?

**Comment by arjun-io** [comment]
Spending more to execute txs is not the same as loss in my opinion 🤷‍♂️

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This is a valid low issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-07-perennial-judging/issues/23/#issuecomment-1690581206): rejected
