### ISSUE TITLE
Emmanuel - Positions will be unfairly liquidated immediately after an unpause

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-perennial-judging#64]
Emmanuel

medium

# Positions will be unfairly liquidated immediately after an unpause
## Summary
While the Market is paused, many positions can become undercollateralized as price of Market token changes.
When the contract gets unpaused, Users are not given the chance to make their positions healthy, which would lead to unfair liquidations.

## Vulnerability Detail
The update function has a `whenNotPaused modifier`:

```solidity
  function update(
        address account,
        UFixed6 newMaker,
        UFixed6 newLong,
        UFixed6 newShort,
        Fixed6 collateral,
        bool protect
    ) external nonReentrant whenNotPaused {
        ...
    }
```

There is no grace period immediately after an unpause when liquidations will be paused.
Due to this, immediately Market gets unpaused, liquidators will liquidate as many undercollateralized positions as possible, while position owners won't have the chance to make their positions healthy.

## Impact
There will be unfair liquidations when Market gets unpaused

## Code Snippet
https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial/contracts/Market.sol#L83

## Tool used

Manual Review

## Recommendation
There should be a grace period immediately after an unpause during which liquidations will be paused.
This will allow position owners to make their positions healthy.

**Comment by Emedudu** [comment]
Escalate

>should be invalid because readme states that the protocol doesn't have any user grace period to come back online in the known issues section

Here is what was stated in known issues section:
"Flywheel being down due to external downtime - sequencer and oracle downtime does not have special case handling. Perennial also does not provide grace periods for users to cure their positions when these systems do come back up".

This does not address the case of unfair liquidations after an unpause(which is not related to external downtime issues)

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> >should be invalid because readme states that the protocol doesn't have any user grace period to come back online in the known issues section
> 
> Here is what was stated in known issues section:
> "Flywheel being down due to external downtime - sequencer and oracle downtime does not have special case handling. Perennial also does not provide grace periods for users to cure their positions when these systems do come back up".
> 
> This does not address the case of unfair liquidations after an unpause(which is not related to external downtime issues), so I think this is a valid M

    You've deleted an escalation for this issue.

**Comment by nevillehuang** [comment]
> Escalate
> 
> > should be invalid because readme states that the protocol doesn't have any user grace period to come back online in the known issues section
> 
> Here is what was stated in known issues section: "Flywheel being down due to external downtime - sequencer and oracle downtime does not have special case handling. Perennial also does not provide grace periods for users to cure their positions when these systems do come back up".
> 
> This does not address the case of unfair liquidations after an unpause(which is not related to external downtime issues), so I think this is a valid M

According to Sherlock’s rule [here](https://docs.sherlock.xyz/audits/judging/judging), should be invalid. 
> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.
